spring:
  application.name: universe
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://host/database"
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: validate # validate, create, create-drop., update, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 100
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  file:
    name: /var/www/pincoinkr/logs/spring.log
  level:
    kr.pincoin.api: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

auth:
  # HS256: openssl rand -hex 24
  # HS384: openssl rand -hex 32
  # HS512: openssl rand -hex 64
  jwt-secret-key: accdfe243ef786e43ca239d13a327b31fc1bdd9d8990fa03

security-config:
  content-security-policy: default-src 'none'
  cors:
    origins: "*"
    headers: "*"
    methods: "*"
    allow-credentials: true